# Generated by Django 4.2.1 on 2023-05-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(default='Lesson description'),
        ),
    ]
