# Generated by Django 4.2.1 on 2023-05-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_group_description_alter_lesson_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
